
compile:
	gcc -Wall assertions.c -o assertions
	gcc -Wall allocate_aligned.c -o allocate_aligned
	gcc -Wall aio.c -o aio
	gcc -Wall blocksize.c -o blocksize
	gcc -Wall madvise-argument.c -o madvise-argument
	gcc -Wall mmap-argument.c -o mmap-argument
	gcc -Wall open-argument.c -o open-argument

clean:
	rm -rf *.o assertions allocate_aligned aio blocksize  madvise-argument mmap-argument open-argument