
compile:
	gcc -Wall assertions.c -o assertions
	gcc -Wall blocksize.c -o blocksize
	gcc -Wall allocate_aligned.c -o allocate_aligned
	gcc -Wall aio.c -o aio
	gcc -Wall madvise-argument.c -o madvise-argument

clean:
	rm -rf *.o filename-fun blocksize allocate_aligned aio madvise-argument